Run pipeline to cache dependencies

diff --git a/.github/workflows/mobile-client-e2e-ios.yml b/.github/workflows/mobile-client-e2e-ios.yml
--- a/.github/workflows/mobile-client-e2e-ios.yml
+++ b/.github/workflows/mobile-client-e2e-ios.yml
@@ -138,33 +138,33 @@ jobs:
         run: |
           curl http://localhost:4723/wd/hub/status || true
 
-      - name: Run Expo app and tests
-        run: |
-          export PATH="$PATH":"$HOME/.maestro/bin"
-          EXPO_PUBLIC_API_URL=${{ env.SERVER_URL }} yarn ios > expo.log 2>&1 &
+      # - name: Run Expo app and tests
+      #   run: |
+      #     export PATH="$PATH":"$HOME/.maestro/bin"
+      #     REACT_NATIVE_PACKAGER_HOSTNAME=127.0.0.1 EXPO_PUBLIC_API_URL=${{ env.SERVER_URL }} yarn ios > expo.log 2>&1 &
 
-          # Wait for Expo to be ready
-          timeout=600  # 10 minutes max
-          while ! grep -q "Waiting on http://localhost:8081" expo.log && [ $timeout -gt 0 ]; do
-          sleep 5
-          timeout=$((timeout - 5))
-          done
+      #     # Wait for Expo to be ready
+      #     timeout=600  # 10 minutes max
+      #     while ! grep -q "Waiting on http://localhost:8081" expo.log && [ $timeout -gt 0 ]; do
+      #     sleep 5
+      #     timeout=$((timeout - 5))
+      #     done
 
-          # Output Expo logs for debugging
-          cat expo.log
+      #     # Output Expo logs for debugging
+      #     cat expo.log
 
-          if [ $timeout -le 0 ]; then
-          echo "Expo did not start within 10 minutes."
-          exit 1
-          fi
+      #     if [ $timeout -le 0 ]; then
+      #     echo "Expo did not start within 10 minutes."
+      #     exit 1
+      #     fi
 
-          # Run your e2e tests
-          yarn test-e2e
-        working-directory: ./client-mobile
+      #     # Run your e2e tests
+      #     yarn test-e2e
+      #   working-directory: ./client-mobile
 
-      - name: Upload Maestro logs and screenshots
-        uses: actions/upload-artifact@v2
-        if: failure()
-        with:
-          name: maestro-logs-and-screenshots
-          path: /Users/runner/.maestro/tests/
+      # - name: Upload Maestro logs and screenshots
+      #   uses: actions/upload-artifact@v2
+      #   if: failure()
+      #   with:
+      #     name: maestro-logs-and-screenshots
+      #     path: /Users/runner/.maestro/tests/
