Use Internal IP as server URL

diff --git a/.github/workflows/mobile-client-e2e-ios.yml b/.github/workflows/mobile-client-e2e-ios.yml
--- a/.github/workflows/mobile-client-e2e-ios.yml
+++ b/.github/workflows/mobile-client-e2e-ios.yml
@@ -55,7 +55,7 @@ jobs:
       - name: Create Settings.toml
         run: |
           cat <<EOT >> ./server/Settings.toml
-          host = "127.0.0.1"
+          host = "0.0.0.0"
           port = "3000"
           postgres_url = "${{ secrets.CI_POSTGRES_URL }}"
           test_postgres_url = "${{ secrets.CI_TEST_POSTGRES_URL }}"
@@ -142,16 +142,25 @@ jobs:
           yarn upgrade
         working-directory: ./client-mobile
 
-      - name: SSH into workflow
-        uses: mxschmitt/action-tmate@v3
+      # - name: SSH into workflow
+      #   uses: mxschmitt/action-tmate@v3
 
       - name: Run Expo app and tests
         run: |
           export PATH="$PATH":"$HOME/.maestro/bin"
           open -a Simulator > simulator.log 2>&1 &
 
+          INTERNAL_IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
+
+          echo "Internal IP: $INTERNAL_IP"
+
+          SERVER_URL=http://$INTERNAL_IP:3000/graphql
+
+          # Check if Internal IP is accessible
+          curl -I -f $SERVER_URL || echo "Cannot reach Internal IP"
+
           # Start Expo and extract the Expo URL
-          EXPO_PUBLIC_API_URL=${{ env.SERVER_URL }} EXPO_PACKAGER_PROXY_URL=http://0.0.0.0:8081 yarn ios > expo.log 2>&1 &
+          EXPO_PUBLIC_API_URL=$SERVER_URL EXPO_TOKEN=${{ secrets.EXPO_TOKEN }} EXPO_PACKAGER_PROXY_URL=http://0.0.0.0:8081 yarn ios > expo.log 2>&1 &
 
           # Wait for Expo to be ready
           timeout=1200  # 20 minutes max
@@ -174,15 +183,8 @@ jobs:
           # Output Expo logs for debugging
           cat expo.log
 
-          INTERNAL_IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
-
-          echo "Internal IP: $INTERNAL_IP"
-
-          # Check if Internal IP is accessible
-          curl -I -f $INTERNAL_IP:8081 || echo "Cannot reach Internal IP"
-
           # Run e2e tests
-          yarn test:e2e -e MAESTRO_APP=exp://0.0.0.0:8081
+          yarn test:e2e
         working-directory: ./client-mobile
 
       - name: Upload Maestro logs and screenshots
